### ISSUE TITLE
only .srt and exercise are downloaded for some courses

### ISSUE THREAD

**Issue by Mozenrat** [r0oth3x49/lynda-dl#10]
Example: "Motion: Principles of Motion Graphics"
No video files, only .srt and exercise files are downloaded for it.

**Comment by r0oth3x49** [comment]
@Mozenrat the reason may be lynda-dl don't download videos in m3u8 stream but a simple .mp4

**Comment by Mozenrat** [comment]
@r0oth3x49, I'm not sure was it related to video format m3u8 or a simple .mp4 when I was trying to download. But I just tried Free Video Download extension for Chrome and it's able to detect and save video as .mp4.  Tried lynda-dl once again, but this time it downloads nothing and just fails with following errors:

```
[*] : Logged in successfully.
[*] : Downloading course information webpages ..
Traceback (most recent call last):
  File "C:\Users\usver\scripts\lynda-dl\lynda-dl.py", line 433, in <module>
    main()
  File "C:\Users\usver\scripts\lynda-dl\lynda-dl.py", line 405, in main
    lynda.InfoExtractor()
  File "C:\Users\usver\scripts\lynda-dl\lynda-dl.py", line 113, in InfoExtractor
    videos_dict = extract_info.real_extract(self.url, course_path)
  File "C:\Users\usver\scripts\lynda-dl\lynda\_extractor.py", line 213, in real_extract
    course              = session.get(curl).json()
  File "C:\Users\usver\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\usver\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\usver\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\usver\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
```
Course URL: https://www.lynda.com/Motion-tutorials/Welcome/75925/80448-4.html

**Comment by rinodung** [comment]
confirm this error: https://www.lynda.com/Drupal-tutorials/Managing-content-Drupal/73655/78769-4.html 
I checked video with mp4 video

**Comment by rackyman** [comment]
The JSONDecodeError happens when the link entered points to a specific video, and not the chapter.

https://www.lynda.com/Motion-tutorials/Welcome/75925/80448-4.html _is the link of the 1st Video_

Whereas,
https://www.lynda.com/Motion-4-tutorials/motion-creating-motion-graphics/75925-2.html _is the link of the course._
Lynda-DL only supports main course link.

**Comment by r0oth3x49** [comment]
@rackyman thanks for your support and explanation.
@Mozenrat, @rinodung  both of you should use the BASE_URL of course rather then giving link of the video.

**Comment by rinodung** [comment]
@r0oth3x49 what is  BASE_URL meaning??? 
Example: https://www.lynda.com/Drupal-tutorials/Managing-content-Drupal/73655/78769-4.html
BASE_URL: ???

**Comment by rackyman** [comment]
@rinodung BASE_URL is the main course url.

**For your example, this is the base/course url :** https://www.lynda.com/Drupal-7-tutorials/essential-training/73655-2.html

**Comment by rinodung** [comment]
thank you so much, Bro!
