### ISSUE TITLE
Connection Resets repeatedly

### ISSUE THREAD

**Issue by satyasaadhak** [r0oth3x49/lynda-dl#12]
This error show up after every few files downloaded. I've run the script ~20 times to complete the download. What's the problem? And is there a fix?

I'm running the command on Ubuntu 16.04 with python 2.7.

![lyndadl-issue](https://user-images.githubusercontent.com/16536094/38367619-d37ad086-3900-11e8-9b76-521cdbec9f89.png)

**Comment by r0oth3x49** [comment]
@itsdpm i will check & fix ASAP. please past the course URL as well.
