### ISSUE TITLE
Can't download entire course

### ISSUE THREAD

**Issue by Drshu** [r0oth3x49/lynda-dl#13]
Hi,
  I tried to download a course [SketchUp: Rendering with V-Ray 3](https://www.lynda.com/SketchUp-tutorials/Software-versions-used-course/599605/662440-4.html), but I just got a part of class.
  Although I got entire chapter list (Had 11 chapter), but some chapters is empty and other chapters only downloaded one video and the subscribe .
 
This is part of log 
```

[*] : Downloading lecture : (1 of 2)
[*] : Downloading (001 Image sampling explained)
[*] : Lecture : '001 Image sampling explained' (already downloaded).

[*] : Downloading lecture : (2 of 2)
[*] : Downloading (001 Image sampling explained.srt)
[*] : Lecture : '001 Image sampling explained.srt' (already downloaded).

[*] : Downloading chapter : (9 of 11)
[*] : Chapter (09  Working with Render Elements)
[+] : Found ('0') lecture(s).
```

  I can't solve this problem, could you give me some helps, Thanks.

**Comment by r0oth3x49** [comment]
@Drshu seems strange i will check & try to reproduce.

**Update**
i just checked it is working fine for me i can see all the lectures in chapter 9.
