### ISSUE TITLE
Course doesn't download

### ISSUE THREAD

**Issue by faisalahammad** [r0oth3x49/lynda-dl#15]
Hi,
I tried to download but it's doesn't work. Here is my Org ID, Pass and Org Name.

`python lynda-dl.py -u 947*** -p 1*** -o ottawa.ca https://www.lynda.com/Web-Development-tutorials/Up-Running-Markdown/438888-2.html`

It's showing me this error http://prntscr.com/j897ma and I'm using Mac and I've installed Python, Pip and brew.

Thanks

**Comment by r0oth3x49** [comment]
@faisalahammad brother you should install the requirements 1st. 
sudo pip install -r requirements.txt
