### ISSUE TITLE
[question] How to use organization url to login ?

### ISSUE THREAD

**Issue by Murtadhajfadhil** [r0oth3x49/lynda-dl#17]
I have Lynda account using ottawa.ca Public Library, and I tried to use this URL to access the account but I failed: ottawa.ca

Thanks in advance 

![screenshot_20180514122845](https://user-images.githubusercontent.com/24244733/39989496-c94e8090-5772-11e8-9084-b7c4094c5c25.png)

**Comment by Murtadhajfadhil** [comment]
@r0oth3x49

**Comment by Murtadhajfadhil** [comment]
@r0oth3x49 please can you look at that?

**Comment by r0oth3x49** [comment]
@Murtadhajfadhil i 'm really very sorry man, i was busy in some other projects i will take a look at this and will guide you ASAP.

**Comment by Murtadhajfadhil** [comment]
@r0oth3x49 
Thank you, bro

**Comment by Murtadhajfadhil** [comment]
@r0oth3x49 
now I'm getting this error 

[*] : Downloading webpage..
[*] : Extracting course information..
[*] : Downloading 'Illustrator CC 2018 One One Advanced'
[*] : Trying to login as organization : (jeffcolibrary.org)...
Traceback (most recent call last):
  File "lynda-dl.py", line 444, in <module>
    main()
  File "lynda-dl.py", line 416, in main
    lynda.InfoExtractor()
  File "lynda-dl.py", line 112, in InfoExtractor
    self.login()
  File "lynda-dl.py", line 35, in login
    extract_info.login(self.user, self.passw, self.org)
  File "C:\Users\Scopesky\Desktop\Courses\Lynda.com\lynda-dl\lynda\_extrac", line 121, in login
    response    = session.post(login_url, data=login_data, headers=std_hea
  File "C:\Users\Scopesky\AppData\Local\Programs\Python\Python36-32\lib\sikages\requests\sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\Scopesky\AppData\Local\Programs\Python\Python36-32\lib\sikages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Scopesky\AppData\Local\Programs\Python\Python36-32\lib\sikages\requests\sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "C:\Users\Scopesky\AppData\Local\Programs\Python\Python36-32\lib\sikages\requests\sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url
requests.exceptions.InvalidSchema: No connection adapters were found for '://www.lynda.com/portal/patron?org=jeffcolibrary.org'

**Comment by r0oth3x49** [comment]
@Murtadhajfadhil are you still facing this error if yes then i might need your credentials to test & fix because i have tested against mine one it works fine for me. you can [email me](mailto:nasir251292@gmail.com) .

**Comment by Murtadhajfadhil** [comment]
@r0oth3x49 just sent you my credentials, thank you

**Comment by r0oth3x49** [comment]
@Murtadhajfadhil its working fine you are using wrong URL use the absolute URL the course you are trying to download is (`https://www.lynda.com/Sass-tutorials/Sass-Essential-Training/375925-2.html`) instead this one (`https://www.lynda.com/Sass-tutorials/Welcome/375925/435554-4.html`).

take a look at screen shot below i have tried to download that course with your credentials and it works fine.
![capture](https://user-images.githubusercontent.com/11024397/40514762-d508092a-5fc3-11e8-8a4a-30b64fca298e.PNG)

**Comment by Murtadhajfadhil** [comment]
@r0oth3x49 
Thank you so much for your effort I really appreciate what are you doing.
But I'm still can't download anything even when I copy and paste your instructions!
I just cloned the latest master of lynda-dl

I sent you an email with more details ..

**Comment by r0oth3x49** [comment]
@Murtadhajfadhil okay try one more time.

- delete lynda-dl completely from your PC.
- then download this [master](https://github.com/r0oth3x49/lynda-dl/archive/master.zip)
- extract to the desktop
- open bash shell as you have opened earlier.
- run the same command i sent to you in terminal.
- check if it works.
**because i have tested with python3 python2, win8.1, win7 both working fine for me.**

**Comment by Murtadhajfadhil** [comment]
@r0oth3x49 
I tried on another computer with win 10 and it worked, but it did not work on my computer with win 7 ultimate with the same procedure (the udemy-dl work efficiently on the same computer)

**Comment by queroin** [comment]
@r0oth3x49 

I have errors too when accessing my organization,
![image](https://user-images.githubusercontent.com/31497266/41451428-73680e94-709f-11e8-9b6a-130f544336e9.png)

but I've also tried barely inputting my organization (cup.okta.com) to lynda and -
![image](https://user-images.githubusercontent.com/31497266/41451685-bf8ff11e-70a0-11e8-8953-61d2a7a8a495.png)

can you fix it? :hammer_and_wrench:

**Comment by subashz** [comment]
I have also csrf token extracting while trying to login with my londonmet.ac.uk organization.
