### ISSUE TITLE
Still have UnicodeEncodeError

### ISSUE THREAD

**Issue by Drshu** [r0oth3x49/lynda-dl#22]
Hi,
  I tried to use the latest lynda-dl and downloaded a course, but still have UnicodeEncodeError.
```

Traceback (most recent call last):
  File "lynda-dl.py", line 456, in <module>
    main()
  File "lynda-dl.py", line 428, in main
    lynda.InfoExtractor()
  File "lynda-dl.py", line 186, in InfoExtractor
    f.write(_data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u266b' in position 4184: ordinal not in range(128)
```

**Comment by r0oth3x49** [comment]
@Drshu course URL required

**Comment by Drshu** [comment]
https://www.lynda.com/Final-Cut-Pro-tutorials/Final-Cut-Pro-X-Weekly/569339-2.html?org=lapl.org

This course cannot worked.I tried again and got a different error:

```
[+] : Downloaded  (003 Adding and adjusting transition effects)

[*] : Downloading lecture : (6 of 26)
[*] : Downloading (003 Adding and adjusting transition effects.srt)
Traceback (most recent call last):
  File "lynda-dl.py", line 456, in <module>
    main()
  File "lynda-dl.py", line 428, in main
    lynda.InfoExtractor()
  File "lynda-dl.py", line 186, in InfoExtractor
    f.write(_data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 14444: ordinal not in range(128)
```

**Comment by tofanelli** [comment]
Here is downloading ok this course... have you tried to remove from ? and after? and how is the command you are using? Something lik

python lynda-dl.py -u #cardLibraryNumer -p #passwordToAccount -o organization LINK

working flawlessly here =)

**Comment by Drshu** [comment]
@tofanelli I tied it again, and this is my command  
`python lynda-dl.py -u ECARD00***** -p **** -o lapl.org https://www.lynda.com/Final-Cut-Pro-tutorials/Final-Cut-Pro-X-10-3-Essential-Training/530433-2.html`

I still got error at same place, but this time the character couldn't encode is \u2019(aka right quote characters)
```
[+] : Downloaded  (003 Auditioning clips to try multiple editing options)

[*] : Downloading lecture : (6 of 12)
[*] : Downloading (003 Auditioning clips to try multiple editing options.srt)
Traceback (most recent call last):
  File "lynda-dl.py", line 456, in <module>
    main()
  File "lynda-dl.py", line 428, in main
    lynda.InfoExtractor()
  File "lynda-dl.py", line 186, in InfoExtractor
    f.write(_data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 1936: ordinal not in range(128)
```

**Comment by tofanelli** [comment]
I just downloaded this whole course with no errors... 

just two silly questions

1- do you have enough space to download them? Yes, is silly but...
2- are you using Windows? If yes, please, take a look on your folder path.. Windows only can deal up to 260 chars to folders names on path. So, if you saving your files on something like

`c:\users\I have a very long user name\desktop\tools\downloaders\lynda-dl\`

Is a long string to be saved.. try to move this tool to a folder in your root drive...

Are you facing any of these issues?

**Comment by Drshu** [comment]
@tofanelli Thanks for your help, but I have enough space and I am using Ubuntu. This is the path `/home/ubuntu/lynda-dl`   

And I tried to  run  this command on a CentOS device, got a same error in same place. That's so weird.

**Comment by tofanelli** [comment]
this seems to be an OS related issue... on Windows I could download this whole course with no problems at all =\

Sorry but only r0ox will be able to help out now =\

**Comment by r0oth3x49** [comment]
@tofanelli thank you for your support :blush: . @Drshu i will test the above course on ubuntu, will try to reproduce and fix ASAP. BTW its weird to see that its working fine for @tofanelli and not for you. any way i will check
