### ISSUE TITLE
Feature to be added

### ISSUE THREAD

**Issue by tofanelli** [r0oth3x49/lynda-dl#23]
Hey man

I was wondering if you can add a feature on this tool... let us create a text file and the program fetch from this file all links I want to batch download... one link per line, would be wonderful...

what you think? =)

**Comment by r0oth3x49** [comment]
@tofanelli great suggestion, will add once i get free time

**Comment by tofanelli** [comment]
Superb! Take your time!!

**Comment by r0oth3x49** [comment]
@tofanelli now you can download courses from a text file.
Example.

`python lynda-dl.py -u user -p pass file_containing_courses.txt`

**Comment by tofanelli** [comment]
you're the real mvp =) ... superb =)
