### ISSUE TITLE
Feature Request - Title Organization Structure Script

### ISSUE THREAD

**Issue by xiSlickix** [r0oth3x49/lynda-dl#24]
Great work on this, looks super promising! I unfortunately can't use your script because I have an organization log in that requires me to use a cookies workaround (in youtube-dl). Is there any chance you could fork the section of code that you wrote to parse the video files names from the website and rename / organize the videos into folders? I ask because youtube-dl spits out filenames in a format similar to "video name-756487" and I presume your code could likely accept arguments for the url of the video series, the folder that contains the downloaded videos, and rename / structure these videos appropriately. I hope that makes sense?

Thanks!
![youtube-dl - lynda](https://user-images.githubusercontent.com/18648663/40860563-d42db00e-65b3-11e8-8693-af54794d3835.png)

**Comment by tofanelli** [comment]
But you have the " - o " flag exactly for this purpose.... and using youtube-dl, as long is extremely verbose to get things done  there, you may be selecting the wrong options... I've been using to download from some other places and the name structure is perfect...

The best part using this tool and Udemy-dl, both of @r0oth3x49 is way less verbose than youtube-dl... I can write down here the command I use on youtube-dl, or you can just use the flag " -o " here, and the result would be

python lynda-dl.py -u USER -p PASSWORD -o ORGANIZATION link

that's it =)

**Comment by xiSlickix** [comment]
I agree that this is less verbose to some degree. My organization uses a SSO authentication and my attempts to use the -o flag have not worked thus far, but passing cookie data to youtube-dl did work. A cookie auth option would be helpful as well in the script.

**Comment by r0oth3x49** [comment]
@xiSlickix i 'm currently working on new release i can add cookies based auth in the next version but for that i might need your account if you are okay with that you can [email me](mailto:nasir251292@gmail.com).

**Comment by xiSlickix** [comment]
Hi r0oth3x49,

I appreciate your quick response to this request! I unfortunately cannot share those credentials as they are tied to other sensitive system (SSO for a college campus). 

The following is pure conjecture - it would seem to me parsing a cookies.txt dump from anyone's credentials would supply you the necessary information to pass along for credential authentication, regardless of single user account of organization information. Maybe the cookies generated are significantly different per account type? Just a thought...

Thanks again

**Comment by r0oth3x49** [comment]
@xiSlickix i didn't checked yet the cookies but suspect the same that cookies should be per account type. i will check with the one account i have

You can can email me cookies i will test with those cookies.
> it would seem to me parsing a cookies.txt dump from anyone's credentials would supply you the necessary information to pass along for credential authentication, regardless of single user account of organization information.

**Comment by r0oth3x49** [comment]
@xiSlickix i 'm closing the issue & will be checking your response on email.
