### ISSUE TITLE
Numbers on lectures

### ISSUE THREAD

**Issue by tofanelli** [r0oth3x49/lynda-dl#25]
Hey @r0oth3x49 ... 

quick quesiton.... i just noticed that lynda-dl resets the lectures numeration on each folder... is there a setting to stop this? I'd rather to let the lectures having a sequentially numeration 

cheers =)

**Comment by r0oth3x49** [comment]
@tofanelli can you please explain a bit more, if you provide an example if would be great to understand whats going on?

**Comment by tofanelli** [comment]
Sure. I will show you using images, would be way easier. Take a look in this image

![image](https://user-images.githubusercontent.com/5512922/40878351-445749fa-6666-11e8-858e-1ecda2fb1ac9.png)

What would be the number of next lecture on the sequential folder? Probably you said 004... right?
![image](https://user-images.githubusercontent.com/5512922/40878365-7a342f0c-6666-11e8-9199-54379c926930.png)

Now you can see =)

**Comment by r0oth3x49** [comment]
@tofanelli i will take care of these extra numbering in next version

**Comment by tofanelli** [comment]
Numbers still resetting 

folder 01
![image](https://user-images.githubusercontent.com/5512922/41054042-a5774db8-6993-11e8-9e28-0896292cb8cf.png)

folder 02
![image](https://user-images.githubusercontent.com/5512922/41054078-c0b09706-6993-11e8-8cb1-acdbaca726a7.png)

Just to let you know.... =)
