### ISSUE TITLE
Renamed 7z to MP4

### ISSUE THREAD

**Issue by tofanelli** [r0oth3x49/lynda-dl#26]
hey @r0oth3x49 ...

quick question...  I downloaded this course [here](https://www.lynda.com/Web-Development-tutorials/Building-Polling-App-Socket-IO-React-js/387145-2.html?) and the tool renamed the exercise file from 7z to 7z.MP4.... I really dunno why this happened, but you might want to take a quick look on it...

Cheers =)

**Comment by r0oth3x49** [comment]
@tofanelli the reason it appends .mp4 at the end is because of hard coded extension type check and not dynamic. this is also fixed in the next release.

**Comment by tofanelli** [comment]
Ok.. superb then =)... waiting for it =)
