### ISSUE TITLE
Error after new version

### ISSUE THREAD

**Issue by tofanelli** [r0oth3x49/lynda-dl#28]
Hey man... 

I just updated to the latest version and getting this error

> Traceback (most recent call last):
  File "lynda-dl.py", line 345, in <module>
    main()
  File "lynda-dl.py", line 341, in main
    lynda.course_download(path=options.output, quality=options.quality)
  File "lynda-dl.py", line 186, in course_download
    lecture_subtitles = lecture.subtitles
  File "F:\Udemy\Lynda\lynda\_shared.py", line 198, in subtitles
    self._process_subtitles()
  File "F:\Udemy\Lynda\lynda\_internal.py", line 111, in _process_subtitles
    subtitles = InternLyndaLectureSubtitles(self._info['subtitles'], self) if se
lf._info['subtitles'].get('subtitle_data') > 0 else {}
TypeError: '>' not supported between instances of 'str' and 'int'

Its not downloading any course =\

**Comment by r0oth3x49** [comment]
@tofanelli i will check and update ASAP.

**Comment by kumaranjeya** [comment]
Hi, It's seems I still can't download the following with latest version:
https://www.lynda.com/Unreal-Engine-tutorials/Unreal-Lighting/456827-2.html

The error as follows:
[*] : Downloading course information .. -Traceback (most recent call last):
  File "lynda-dl.py", line 344, in <module>
    main()
  File "lynda-dl.py", line 340, in main
    lynda.course_download(path=options.output, quality=options.quality)
  File "lynda-dl.py", line 153, in course_download
    course = lynda.course(url=self.url, username=self.username, password=self.password, organization=self.organization)
  File "C:\lynda-dl\lynda\_lynda.py", line 38, in course
    return Lynda(url, username, password, organization, basic, callback)
  File "C:\lynda-dl\lynda\_internal.py", line 43, in __init__
    super(InternLyndaCourse, self).__init__(*args, **kwargs)
  File "C:\lynda-dl\lynda\_shared.py", line 61, in __init__
    self._fetch_course()
  File "C:\lynda-dl\lynda\_internal.py", line 52, in _fetch_course
    self._info              =       self._real_extract(self._url)
  File "C:\lynda-dl\lynda\_extract.py", line 273, in _real_extract
    sources = self._extract_sources(course_id, lecture_id)
  File "C:\lynda-dl\lynda\_extract.py", line 198, in _extract_sources
    _max_stream = max(map(self._get_max_stream, _stream_720))
TypeError: '>' not supported between instances of 'dict' and 'dict'

Any help? Thank you.

**Comment by r0oth3x49** [comment]
@kumaranjeya i cannot reproduce. works fine for me
![capture](https://user-images.githubusercontent.com/11024397/41038722-9a196cf4-69b0-11e8-87cf-4367036d429a.PNG)

**Comment by r0oth3x49** [comment]
@kumaranjeya i have added a fix again clone again & then try to download

**Comment by kumaranjeya** [comment]
Hi, what can i say...it's superb. All working now. Thank you so much. Keep up the good work. Regards.

**Comment by kumaranjeya** [comment]
Sorry if i'm writing in wrong area. Any chance of creating similar for Pluralsight download? Thank you for your consideration. Regards

**Comment by tofanelli** [comment]
@kumaranjeya you can use youtube-dl... work smoothly =)

**Comment by kumaranjeya** [comment]
Yes. I have tried works great but it doesn't download *.zip work files for that particular course only videos.

**Comment by tofanelli** [comment]
yeah.... unfortunately they need to be downloaded later on.... I haven't seen any option to download them together too =\
