### ISSUE TITLE
sometimes can't download the whole course with my library card authorization

### ISSUE THREAD

**Issue by HoldOnBro** [r0oth3x49/lynda-dl#3]
I‘ve been using this great script for 3 days and have downloaded some lynda videos. Within my use, I encountered some bugs to which I can't find a resolution as I am learning Python and not good at it. Wish this can help make a better lynda-dl.
MY OS is windows 10 and my membership is organization authorization.
some courses's links work just fine, while 
https://www.lynda.com/Python-tutorials/Python-3-Essential-Training/62226-2.html
this link can only pull down the subtitles.
and this 
https://www.lynda.com/Digital-Photography-tutorials/foundations-of-photography-exposure/71923-2.html
can only download about 80% of the whole.
I did the test with python2.7.14 and python 3.6.3, they both have this problem.

I guess this is because those two course links are too old(around 2010)that the pages have some different formats or the video ids are different from the newer courses.
BTW, I tried this 
https://www.lynda.com/Photography-tutorials/foundations-of-photography-lenses/76336-2.html
and all just work fine. this course is 2011.

Actually, despite these little bugs, lynda-dl is still the best python script for downloading the Lynda courses.(I tried almost every script I can find, even the youtube-dl is still has a problem as I can't download a whole course no matter how new the course is or what the course is, it just can't work)

**Comment by r0oth3x49** [comment]
@k432ts thanks for the appreciation & sorry for the late response. i will debug the script against these courses and will update ASAP.
