### ISSUE TITLE
Zip file download error

### ISSUE THREAD

**Issue by kumaranjeya** [r0oth3x49/lynda-dl#31]
I'm keep getting following error:
[*] : Downloading asset(s)
[*] : Downloading (Ex_Files_UaR_MayaLT_2016.zip)
[*] : Asset : 'Ex_Files_UaR_MayaLT_2016.zip' (download skipped).
[-] : URLError : either your internet connection is not working or server aborted the request

These are the courses that has the error:
https://www.lynda.com/Maya-tutorials/Up-Running-Maya-LT/408407-2.html
https://www.lynda.com/Illustrator-tutorials/Drawing-Vector-Graphics-Laboratory/475456-2.html

**Comment by r0oth3x49** [comment]
@kumaranjeya i will fix this ASAP.
