### ISSUE TITLE
Error "Failed to extract log-in form"

### ISSUE THREAD

**Issue by k0th31** [r0oth3x49/lynda-dl#34]
Dear Khan,

Your new v0.2 is having subjected error "Failed to extract login form". So, I am re-using old script which still works better.
I use Python 3.6.5. Version v0.1 (Jun 3) is okay.

**Comment by oyedeyeye** [comment]
I am having similar issues with the new version. I just installed everything afresh, including python 3. and the -r requirements.txt

**Comment by oyedeyeye** [comment]
It is now Working.... @r0oth3x49  Thank you
