### ISSUE TITLE
Error on naming courses

### ISSUE THREAD

**Issue by tofanelli** [r0oth3x49/lynda-dl#35]
hey man... 

this is not quite an issue but, every time the scripts rips a course with "2018" (it can be any year, actually) the course name goes to  "E18" instead... take a look using this link
`https://www.lynda.com/Illustrator-tutorials/Illustrator-CC-2018-One-One-Fundamentals/633853-2.html`

Cheers =)

**Comment by k0th31** [comment]
Is this applicable in V0.2???

**Comment by tofanelli** [comment]
yup.... latest version...

**Comment by k0th31** [comment]
@tofanelli May I know how to use V0.2. I installed requirements.txt. PIP INSTALL -R REQUIREMENTS.TXT
But, it bounced with message "Failed to extract login-form".
I use Windows 7. Python 3.6.5.
Please help me.

**Comment by r0oth3x49** [comment]
@k0th31 i have added a fix for the error you were facing try to clone the recent master and then use if you still face any error let me know.

**Comment by r0oth3x49** [comment]
@tofanelli i will check & fix ASAP.

**Comment by tofanelli** [comment]
hey @r0oth3x49 ...

thanks for fixing this issue... but now, another one came up with this fix... check [this course](https://www.lynda.com/PHP-tutorials/Easy-PHP-Projects-Measurement-Conversion/418852-2.html) as an example. There is no need to rip the entire course, only the description...

Noticed that the first words are italic (em tag), the previous Lynda-dl version, wasn't parsing the code, so,  it was bringing the raw HTML code to the description file, like 
`<em> EASY PHP.... </em>`
and in this new version, it parses but brings an "undecoded" html tags... 

and plus, in this new version, the scrapper is not obeying the paragraphs... turns everything into a huge paragraph instead breaking as in the description in the Lynda website...  you will understand with this same link provided above....

If its not easy to understand what I said, just let me know and I will show you some images to make it clear =)


Cheers =)

**Comment by tofanelli** [comment]
hey @r0oth3x49 ... still on naming, check [this one](https://www.lynda.com/Java-tutorials/3D-graphics-JavaFX/572154-2.html) when ripped... missing the 3 on 3D....

**Comment by r0oth3x49** [comment]
@tofanelli i will check both of the above on this weekend

**Comment by tofanelli** [comment]
Superb @r0oth3x49 ... another thing i just noticed... check [this link](https://www.lynda.com/Android-Studio-tutorials/Android-Studio-Essential-Training/677172-2.html)... there is a question mark in the first paragraph... right? So, the scrapper removed it.... Hope this may lead you to solve =)
