### ISSUE TITLE
Error downloading when courses have special characters?

### ISSUE THREAD

**Issue by Bneboy** [r0oth3x49/lynda-dl#37]
```
Traceback (most recent call last):
  File "C:\Programs\lynda-dl\lynda-dl.py", line 349, in <module>
    main()
  File "C:\Programs\lynda-dl\lynda-dl.py", line 345, in main
    lynda.course_download(path=options.output, quality=options.quality)
  File "C:\Programs\lynda-dl\lynda-dl.py", line 172, in course_download
    course.course_description(filepath=course_path)
  File "C:\Programs\lynda-dl\lynda\_shared.py", line 126, in course_description
    f.write(data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 814: ordinal not in range(128)
Press any key to continue . . .
```

I got this crash on Windows 10 PC using Python 2.7.15
I tried DL'ing a course where in the description has special characters. It worked for me on other courses, others without these special characters. The only word with special characters seems to be "résumé", on the Lynda page for it.

**Comment by r0oth3x49** [comment]
@Bneboy course URL? btw i have recently pushed an updates to this repo where this issue is already fixed did you tried with latest `master`

**Comment by Bneboy** [comment]
https://www.lynda.com/CSS-tutorials/CSS-Essential-Training-1/569190-2.html is the URL.
