### ISSUE TITLE
Supporting LinkedIn Learning

### ISSUE THREAD

**Issue by ScorpionIbm** [r0oth3x49/lynda-dl#39]
Can I use this to download videos from LinkedIn Learning instead of Lynda?
As I don't have an account on Lynda and can't link my LinkedIn account to Lynda

**Comment by r0oth3x49** [comment]
@ScorpionIbm can you please explain a bit more. it will be great if you can share some examples & screenshots in your explanation then i will guide you.

**Comment by ScorpionIbm** [comment]
LinkedIn learning [https://www.linkedin.com/learning/](https://www.linkedin.com/learning/) is a rebrand of Lynda that has the same courses but your script refuses to use my login credentials ... The script says Lynda doesn't recognize login.

**Comment by ScorpionIbm** [comment]
Also linkedIn Learning has an API [here](https://docs.microsoft.com/en-us/linkedin/learning/overview/) If this would make it easier for supporting downloads from it

You can have a look at this project if it would help [https://github.com/mclmza/linkedin-learning-downloader](https://github.com/mclmza/linkedin-learning-downloader)

**Comment by r0oth3x49** [comment]
@ScorpionIbm i can add support for this. but you can still download the same course with *lynda-dl* what you need to do is to google the course name followed by Lynda. Google will show you the url supported by this repository and then you can download that using your credentials. but i will take a look at this. for this i might need your credentials if you are okay with sharing then you can [email me](mailto:nasir251292@gmail.com)

**Comment by ScorpionIbm** [comment]
Sadly my credentials aren't accepted on Lynda as they only work for LinkedIn learning (Lynda.com doesn't recognize my login credentials).

Secondly, I can't send my linkedIn credentials because they give access to the whole LinkedIn profile and payment info not just LinkedIn learning, but you can make an account with a month of free trial [here](https://www.linkedin.com/learning/).
Also I can help you with testing.

Thanks for your fast response. I'd be glad if you could make your script work for that too as it's more advanced and stable with more features.

**Comment by ScorpionIbm** [comment]
![lynda](https://user-images.githubusercontent.com/8678254/43035226-4f083b46-8cec-11e8-8328-ca02b62d6efb.PNG)
This is what the script shows when I try to login with my credentials on LinkedIn Learning

**Comment by r0oth3x49** [comment]
@ScorpionIbm okay i understand and respect your privacy. If you can't then the other solution could be using cookie based authentication. or i will check with some free contents & can you share the course url you are trying to download?

**Comment by ScorpionIbm** [comment]
It's a complete learning Path [here](https://www.lynda.com/learning-paths/Design/become-a-digital-illustrator) If the script doesn't work with that then the individual course links in there should work

**Comment by Abhi904485** [comment]
hi @r0oth3x49  i am also having same problem now lynda courses are accessible through linkedin learning , i tried myself to make some change in script

> @ScorpionIbm i can add support for this. but you can still download the same course with _lynda-dl_ what you need to do is to google the course name followed by Lynda. Google will show you the url supported by this repository and then you can download that using your credentials. but i will take a look at this. for this i might need your credentials if you are okay with sharing then you can [email me](mailto:nasir251292@gmail.com)

you can check this thing with your credentails . 

i tried the way you told to search in google , In 6 hrs of course only public lectures Downloaded , other lectures skipped .
