### ISSUE TITLE
Connection error : make sure your internet connection is working.

### ISSUE THREAD

**Issue by RobertHosking** [r0oth3x49/lynda-dl#41]
I'm running this on a remote Ubuntu server

The command:
`$ python lynda-dl.py -o myuniversity.edu -u myusername -p thepassword https://www.lynda.com/Writing-tutorials/Writing-Compelling-Blog-Post/642461-2.html`

The output:
`[*] : Trying to login as organization (myuniversity.edu)...`
`[-] : Connection error : make sure your internet connection is working.`

The interenet is obviously working since I can ssh to the remote server.

Any tips?

**Comment by r0oth3x49** [comment]
@RobertHosking can you please explain a bit more like which ubuntu server it is? python version etc?

- have you updated all the requirements.txt. if not then upgrade to latest one.
- try upgrading `requests[security]` & then try to download.

**Comment by RobertHosking** [comment]
Thanks for the quick response! My organization access is being revoked soon (graduated) and I'm trying to milk it while I can!

- Ubuntu 16.04 on Digital Ocean
- Python 2.7.12
- pip version 18.0

After
`sudo pip install --upgrade --force-reinstall -r requirements.txt`
I run the same command in my OP and get the same error:
`[-] : Connection error : make sure your internet connection is working.`

**Comment by r0oth3x49** [comment]
@RobertHosking i will try to reproduce and fix ASAP.

**Comment by TheMedOne** [comment]
@RobertHosking I had the same issue while downloading the course , to fix id i had to upgrade to python3 , hope that is working for you

**Comment by sugesh1137** [comment]
I too have been facing the same issue! Is there any fix ??

Let me paste some evidences here..

[root@localhost acloud-dl]# python3 acloud-dl.py -c file_containing_cookie.txt --info

              __                __          ____
  ____ ______/ /___  __  ______/ /     ____/ / /
 / __ `/ ___/ / __ \/ / / / __  /_____/ __  / /
/ /_/ / /__/ / /_/ / /_/ / /_/ /_____/ /_/ / /
\__,_/\___/_/\____/\__,_/\__,_/      \__,_/_/

                                 Version : 0.1
                                 Author  : Nasir Khan (r0ot h3x49)
                                 Github  : https://github.com/r0oth3x49

[-] : Connection error : make sure your internet connection is working.
[root@localhost acloud-dl]#

I was facing cookies issues initially, but got that sorted. Below was the error..

[-] : Cookies error, Request Headers is required...
[i] : Copy Request Headers for single request to a file, while you are logged in.

So I was able to get through with the help of https://github.com/r0oth3x49/udemy-dl/issues/303#issuecomment-441345792 

But now i am stuck here. 

Note: When I disconnect and reconnect my internet, it does pass through one more step, but again throw me the same error. Let me demonstrate that..

[root@localhost acloud-dl]# python3 acloud-dl.py -c file_containing_cookie.txt --info

              __                __          ____
  ____ ______/ /___  __  ______/ /     ____/ / /
 / __ `/ ___/ / __ \/ / / / __  /_____/ __  / /
/ /_/ / /__/ / /_/ / /_/ / /_/ /_____/ /_/ / /
\__,_/\___/_/\____/\__,_/\__,_/      \__,_/_/

                                 Version : 0.1
                                 Author  : Nasir Khan (r0ot h3x49)
                                 Github  : https://github.com/r0oth3x49

[*] : Downloading accessible courses information .. (done)
[1] : Introduction to Kubernetes
[2] : Certified Kubernetes Administrator (CKA)
[?] : select course number or range (1/2/range): 1+

[*] : Course 'Introduction to Kubernetes'.
[-] : Connection error : make sure your internet connection is working.

This is just after I restart my internet connection..

Really appreciate your work! Hope to pass through this too. 
Thank you in advance!
