### ISSUE TITLE
Failed to extract csrftoken

### ISSUE THREAD

**Issue by TheOtherKraits** [r0oth3x49/lynda-dl#42]
I'm trying to use lynda-dl with my university login but I am getting the error:
` Failed to extract csrftoken.`
after I input my username and password

My input was:
`python lynda-dl.py -o insertuniversityhere.edu  https://www.lynda.com/Python-tutorials/Learning-Python/661773-2.html`

I'm running on Windows 10 64-bit with Python 3.6

**Comment by r0oth3x49** [comment]
@TheOtherKraits  works fine for me i cannot reproduce.

![capture](https://user-images.githubusercontent.com/11024397/44029511-0405985e-9f17-11e8-965b-68ed846ce682.PNG)


can you try the below command.
```
python lynda-dl.py -u your_user -p your_password -o insertuniversityhere.edu https://www.lynda.com/Python-tutorials/Learning-Python/661773-2.html
```

**Comment by TheOtherKraits** [comment]
@r0oth3x49 I just tried it and got the same error. Can I email you my organization? I believe the issue is with how my organization's login works. I get the error when I try it with an incorrect login as well as the correct one.

**Comment by r0oth3x49** [comment]
@TheOtherKraits yes you can [email me](mailto:nasir251292@gmail.com). i will test and try to fix the issue ASAP.

**Comment by TheOtherKraits** [comment]
@r0oth3x49 Thanks! email sent.

**Comment by martijnkruiten** [comment]
The same happens with an organization I am using. I've just emailed you which organization I'm talking about.

**Comment by maciozo** [comment]
Apologies for reviving a closed issue, but I'm getting the same problem. Running Python 3.6.6 on MSYS2 on Windows 8.1. Using incorrect cridentials has the same result.

![image](https://user-images.githubusercontent.com/15807067/49110706-1a903d00-f286-11e8-9f40-3c200c70cce6.png)

Using cookies results in a login failure:

![image](https://user-images.githubusercontent.com/15807067/49111032-ea956980-f286-11e8-9a4d-7d376718c540.png)
