### ISSUE TITLE
Failed to login with SSO credentials

### ISSUE THREAD

**Issue by anandchavan** [r0oth3x49/lynda-dl#43]
In my organisation we get the lynda subscription by logging in to lynda with sso login credentials, in this case I am unable to download

**Steps to reproduce -** 

```
1. Lynda Course URL - https://www.lynda.com/AutoCAD-training-tutorials/160-0.html
2. Organization name - example.com ( for sample )
2.  Enter command -
python udemy-dl.py <course_url> -o <org_name>
```

**Expected -** Login and Download to start

**Actual -** 

```
[*] : Username : user_name
[*] : Password : ****
[*] : Trying to login as (user_name)...
[-] : Failed to login ..
```

**Comment by r0oth3x49** [comment]
@anandchavan i might need your account to add support for SSO based accounts. you can [email me](mailto:nasir251292@gmail.com)

**Comment by anandchavan** [comment]
@r0oth3x49 
Sharing account will be against policy.

However, I feel that the cookie support like which youhave given for udemy will help.

I may help you to test with the test branch once you start the implementation

**Comment by r0oth3x49** [comment]
@anandchavan sounds great, then i 'm closing this issue with enhancement and when i get some time i will implement.
