### ISSUE TITLE
Subtitle file name is not the same as the video name

### ISSUE THREAD

**Issue by qqfreshman** [r0oth3x49/lynda-dl#47]
@r0oth3x49 I'm using the latest v0.3 and find the subtitle file name is not the same as the video name. So the subtitle can't load automatically when I watch the video. Is it possible to fix it in the next version?
By the way, I'm using CentOS 6 with Python 2.7+Pip 9.0
![subtitle and video name are not the same](https://user-images.githubusercontent.com/31643883/48075625-a4685f80-e21e-11e8-9958-41b44aac35d2.jpg)

**Comment by r0oth3x49** [comment]
@jw587 if a use the same name as video, then at the end you will only be having the subtitle which is downloaded at the end.

let say, a video have multiple subtitles (English, Spanish etc)
if i don't use the suffix for one at the end the you will only have the one subtitle file downloaded at end.

so technically this isn't a bug or an error but a solution for multi captions.

**Comment by qqfreshman** [comment]
@r0oth3x49 Got it. Thanks. I'll try to find some solution from the video player side to load the EN subtitle automatically.
