### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by jaan143** [r0oth3x49/lynda-dl#48]
hello i am getting this error (Failed to extract login form)

**Comment by leninkumark** [comment]
Me too :-(

**Comment by jaan143** [comment]
@r0oth3x49  bro how can i give you detail ?
i dont understand but actually lynda is updated so thats the reason this script is not working
it was working fine 4 days ago

**Comment by r0oth3x49** [comment]
@jaan143 you can [email me](mailto:nasir251292@gmail.com). for me it still works

**Comment by bluekar** [comment]
yeah me too, and I tried another PC and Mac are same
