### ISSUE TITLE
Skip Excercise Files From Downloading

### ISSUE THREAD

**Issue by jawidjrs** [r0oth3x49/lynda-dl#50]
Hi, Thank you for this great program.
I would like to know if there is a function or ability to skip or choose between hi resolution or low resolution exercise files to be downloaded during the process.
Below is a link to a course in Lynda.com only for example and test:
https://www.lynda.com/Photoshop-tutorials/Photoshop-Retouching-Techniques-Faces/141134-2.html

**Comment by r0oth3x49** [comment]
@jawidjrs there is a option which you can use to download the requested resolution. use `-q or --quality` switch.

> exercise files to be downloaded during the process.
can you please explain this a bit more.

**Comment by jawidjrs** [comment]
Thank you for your response.
I would like to know if there is an option for example to skip or prevent exercise files to be downloaded alongside the course videos.
Some courses provide two zip files as exercise files especially in the design tutorial category. one with a larger size and the other one same content but with more compressed and smaller size. but I noticed that the lynda-dl will download both files. that I have problem with.

best regards
Jawid

**Comment by r0oth3x49** [comment]
no currently there is no such option which can be used to skip assets / exercise files. I will consider this as enhancement.
