### ISSUE TITLE
how do I download more than one course(web links) at one session

### ISSUE THREAD

**Issue by jawidjrs** [r0oth3x49/lynda-dl#51]
Hi there,
I wonder if it's possible to add more than one link of a course tutorial where the "COURSE_URL" should be inserted.
Thanks 
Yours truly,
Jawid

**Comment by r0oth3x49** [comment]
@jawidjrs it is already there, if you would have checked the **Advance Usage**.

either you provide course url or a file containing list of course urls separated by new line. 
let say :-
course01_url
course02_url
and so on.

Lynda will download all those course listed in the text file.

**Edit**
Steps.
 - copy paste the course urls to text file separated by new line.
 - run the code
    ```python
     python lynda-dl.py -u user -p pass courses.txt
    ```

**Comment by jawidjrs** [comment]
I'm sorry but there is no such file named course.txt

**Comment by hereisderek** [comment]
never knew you could do that, spent so much time wrapping it in a while loop
(with additional features such as tracking/moving successful downloads etc.)
