### ISSUE TITLE
How to resume a partially downloaded course

### ISSUE THREAD

**Issue by jawidjrs** [r0oth3x49/lynda-dl#53]
Hi,
I have a course partially downloaded for an unknown error yesterday. because the files was big in size, Now I want to resume chapters but not entire course from the beginning.
I'd appreciated if you please guide me how to do this.
Thank you very much,
Jawidjrs

**Comment by r0oth3x49** [comment]
@jawidjrs run the code against that specific course it will start where it left automatically. by default it checks for the course in current directory if not available it starts from beginning if its there will resume where it left.

**Comment by jawidjrs** [comment]
It is downloading from where it left.
Thank you very much for your quick response.
Jawidjrs
