### ISSUE TITLE
 JSONDecodeError : it seems your cookies got expired, provide again.

### ISSUE THREAD

**Issue by AntiGov** [r0oth3x49/lynda-dl#55]
JSONDecodeError : it seems your cookies got expired, provide again.
the error happened only if course flaged with icon locked which mean the authenticated user dont have access to the course

**Comment by Raamakrishnan** [comment]
Getting the same error. But I have access to the video normally in the browser. Any way I can help to find the issue? A log perhaps?

**Comment by r0oth3x49** [comment]
@AntiGov i will take a look at this issue and fix ASAP. sorry for late response.

**Comment by Abhi904485** [comment]
> @AntiGov i will take a look at this issue and fix ASAP. sorry for late response.

Actually lynda is upgraded to Linkedin Learning that why it is showing Cookie Expired any lynda dl is not working in new up-gradation because course url is changed .

**Comment by manu212** [comment]
will this ever be fixed? is there an alternative downloader which can be used meanwhile?

**Comment by Abhi904485** [comment]
We need to change all urls in regular expression and some code refactoring after that it will work

**Comment by biplobsd** [comment]
Fix this issue (ASAP). We need your tools. Your tools is great.

**Comment by AntiGov** [comment]
> > @AntiGov i will take a look at this issue and fix ASAP. sorry for late response.
> 
> Actually lynda is upgraded to Linkedin Learning that why it is showing Cookie Expired any lynda dl is not working in new up-gradation because course url is changed .

this is not the case, the problem as i mention above the error accrued only when course flaged as locked, which mean you dont have access to it

**Comment by manu212** [comment]
in my case it happens with all videos

**Comment by manu212** [comment]
any update on this or useful workaraounds/alternatives?

**Comment by WaxKitten** [comment]
2 different error :(

![4](https://user-images.githubusercontent.com/33392588/54490640-8693c100-48c8-11e9-89cf-c5e181d8f0d4.png)
&
![5](https://user-images.githubusercontent.com/33392588/54490641-872c5780-48c8-11e9-81c3-e9f0e7978297.png)

**Comment by nomanali1** [comment]
I am getting this error ever since I download lynda-dl. I can't seems to resolve this issue. I have tried EditThisCookie, Export Cookies.txt extention for cookies. They don't seems to work. Also I tried copy request headers from inspect. That does't work also. Help me out here please.


![Annotation 2019-03-25 231223](https://user-images.githubusercontent.com/11135482/54943631-82fcdb80-4f53-11e9-8f16-b7aa4cb3a043.jpg)

**Comment by manu212** [comment]
any update?

**Comment by controversy187** [comment]
I was running into this issue as well. Turns out that if a video doesn't have a valid subtitle file, Lynda returns invalid JSON which causes lynda-dl to fail. Try executing with the --skip-sub option. Also, I have a PR that fixed the issue (for me).

**Comment by manu212** [comment]
@controversy187 what does PR mean?

**Comment by controversy187** [comment]
Pull Request. I wrote a patch for this code and have requested that it be merged into the main project. In the meantime, have you tried downloading with the --skip-sub option? I didn't test that, but I think that would have fixed the issue (in my case), as I don't need the subs.

**Comment by fmunirdev** [comment]
@controversy187 I tried with the `--skip-sub` option but didn't fixed the issue.

**Comment by r0oth3x49** [comment]
@AntiGov the error could be resolved by providing the new cookies, the session gets expired which leads to this error, so if you refresh your session in browser and provide the cookie again it will work fine.

**Comment by ahmed-alii** [comment]
I'm logging in with organization portal. No cookies involved in it. Still getting this error.

**Comment by r0oth3x49** [comment]
@ahmed-alii can you please explain a bit more?
