### ISSUE TITLE
Empty description file of courses

### ISSUE THREAD

**Issue by WaxKitten** [r0oth3x49/lynda-dl#56]
Downloaded text file of courses are empty. Is it just me?
Can you add those to text file if you're thinking of rebuild:

Description
/
DescriptionDescriptionDescriptionDescription
DescriptionDescriptionDescription
/

Author: xxxxx yyyyyyy
Released xx/xx/xxxx
Skill Level: Beginner/Appropriate for all/etc
Duration: 3h 18m

Topics include: 
   •xxxxxxxxx
   •yyyyy
   •zzzzzzzzzzz
   •ffff
   •tttttttttt

Subjects:
Business / Data Analysis / Project Management / etc

Software
Github / Excel / After Effects / etc

**Comment by r0oth3x49** [comment]
@WaxKitten i will wait for others to endorse and then will check if there is any provision to implement.

**Comment by WaxKitten** [comment]
Will it fix ? @r0oth3x49

**Comment by r0oth3x49** [comment]
@WaxKitten can you explain why you want to add all those things? it think long/short descriptions are good enough isn't?

**Comment by WaxKitten** [comment]
This txt problem solved by using linux.

**Comment by Medow** [comment]
> This txt problem solved by using linux.

How do you solve the description error?
i am using ubuntu and the description file is always empty when downloading courses.
Thanks.
