### ISSUE TITLE
How to resolve  "JSONDecodeError : it seems your cookies got expired, provide again."  ?

### ISSUE THREAD

**Issue by mikelee281756** [r0oth3x49/lynda-dl#57]
Why occur the above error?How to solve?
My lynda-dl code is download through "Clone or download" button in the URL:https://github.com/r0oth3x49/lynda-dl
And the lynda-dl code is unzipped in the directory E:\tools\lynda-dl-master\lynda-dl-master on my win7 64 OS
Following is the run steps in cmd window on win7 64bit:
/////////////////////////////////////////////////////////////////////////
C:\Users\Administrator>e:

E:\>cd E:\tools\lynda-dl-master\lynda-dl-master

E:\tools\lynda-dl-master\lynda-dl-master>python lynda-dl.py -u 5296491.199368077
5 -p bfhroi528 -d F:\lynda\subtitles --sub-only https://www.lynda.com/Digital-Ph
otography-tutorials/foundations-of-photography-exposure/71923-2.html

 oooo                                .o8                      .o8  oooo
 `888                               "888                     "888  `888
  888  oooo    ooo ooo. .oo.    .oooo888   .oooo.        .oooo888   888
  888   `88.  .8'  `888P"Y88b  d88' `888  `P  )88b      d88' `888   888
  888    `88..8'    888   888  888   888   .oP"888 8888 888   888   888
  888     `888'     888   888  888   888  d8(  888      888   888   888
 o888o     .8'     o888o o888o `Y8bod88P" `Y888""8o     `Y8bod88P" o888o
       .o..P'
       `Y8P'                            Version : 0.3
                                        Author  : Nasir Khan (r0ot h3x49)
                                        Github  : https://github.com/r0oth3x49

[*] : Trying to login as (5296491.1993680775)...
[+] : Logged in successfully.
[*] : Downloading course information .. -
[-] : JSONDecodeError : it seems your cookies got expired, provide again.

**Comment by shumbashi** [comment]
Same issue here

**Comment by r0oth3x49** [comment]
@mikelee281756 , @shumbashi lets discuss this issue at #55. i 'm closing it from here
