### ISSUE TITLE
username and password should be option

### ISSUE THREAD

**Issue by ThetNaingTun2019** [r0oth3x49/lynda-dl#58]
Some links in lynda is open to all without username and password.
In such case, your script is waiting to verify username and password, which is not required for open access link.
e.g https://www.lynda.com/Kotlin-tutorials/Anko-coroutines-Launch-basics/642478/710027-4.html

This course is open to all. But, your script cannot download if I cannot provide proper username and password for lynda.
Nowadays, lynda is difficult to get username and password. Instead, linkedin is being redirected.

Kindly consider to make optional for username and password.

**Comment by r0oth3x49** [comment]
@ThetNaingTun2019 i will check the possibility and will implement.
