### ISSUE TITLE
list download broken

### ISSUE THREAD

**Issue by manu212** [r0oth3x49/lynda-dl#66]
[+] : Logged in successfully.
Traceback (most recent call last):on ..
  File "lynda-dl.py", line 395, in <module>
    main()
  File "lynda-dl.py", line 301, in main
    lynda.course_download(path=options.output, quality=options.quality)
  File "lynda-dl.py", line 162, in course_download
    course = lynda.course(url=self.url, username=self.username, password=self.password, organization=self.organization, cookies=self.cookies)
  File "C:\Users\x\Documents\portable_apps\lynda-dl-master\lynda\_lynda.py", line 38, in course
    return Lynda(url, username, password, organization, cookies, basic, callback)
  File "C:\Users\x\Documents\portable_apps\lynda-dl-master\lynda\_internal.py", line 43, in __init__
    super(InternLyndaCourse, self).__init__(*args, **kwargs)
  File "C:\Users\x\Documents\portable_apps\lynda-dl-master\lynda\_shared.py", line 65, in __init__
    self._fetch_course()
  File "C:\Users\x\Documents\portable_apps\lynda-dl-master\lynda\_internal.py", line 55, in _fetch_course
    self._info              =       self._real_extract(self._url)
  File "C:\Users\x\Documents\portable_apps\lynda-dl-master\lynda\_extract.py", line 242, in _real_extract
    response = self._session.get(url)
  File "C:\Users\x\Documents\portable_apps\WPy-3670\python-3.6.7\lib\site-packages\requests\sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\x\Documents\portable_apps\WPy-3670\python-3.6.7\lib\site-packages\requests\sessions.py", line 510, in request
    prep = self.prepare_request(req)
  File "C:\Users\x\Documents\portable_apps\WPy-3670\python-3.6.7\lib\site-packages\requests\sessions.py", line 453, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\x\Documents\portable_apps\WPy-3670\python-3.6.7\lib\site-packages\requests\models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "C:\Users\x\Documents\portable_apps\WPy-3670\python-3.6.7\lib\site-packages\requests\models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'requests[security]': No schema supplied. Perhaps you meant http://requests[security]?

**Comment by r0oth3x49** [comment]
@manu212 list download is not broken, you might have done something wrong while providing list of urls. the error clearly says that your provided url is invalid or broken. its a human error. if you are trying to download multiple courses using file then you should create a text file containing list of course urls separated by new line.

Example.
course_01
course_02

**Comment by controversy187** [comment]
@manu212 Based on the error, it looks like you may have forgotten the "https://" from your URLs.

**Comment by manu212** [comment]
unfortunately not, i tried with one URL with https, without, etc. can you provide me an example file with three real existing URLs which i can access with lynda-dl?

Thanks a lot.

I followed your diskussion in the issues and README: URLs separeted by New lines in a text file. My URLs work as a single download parameter, but not in a text file list. So there is no typing mistake

**Comment by r0oth3x49** [comment]
[courses.txt](https://github.com/r0oth3x49/lynda-dl/files/3240780/courses.txt)
![Capture](https://user-images.githubusercontent.com/11024397/58698448-bc6b2080-83b4-11e9-8fa1-55ceadb90721.PNG)

**Comment by manu212** [comment]
i found the issue: the url-download works with: https://www.lynda.com/Developer-tutorials/Python-Projects/604246-2.html, but list download requires the full url like your example. nevertheless the list download works with organizational login only once. the second url gives a "JSONDecodeError : it seems your cookies got expired, provide again.". This is because of auto logging out through lynda-dl. THen the cookie is invalid. Login with username and password s not possible, since authentication is made through the organisation portal...

Is this a known bug?

**Comment by r0oth3x49** [comment]
> 
> 
> i found the issue: the url-download works with: https://www.lynda.com/Developer-tutorials/Python-Projects/604246-2.html, but list download requires the full url like your example. nevertheless the list download works with organizational login only once. the second url gives a "JSONDecodeError : it seems your cookies got expired, provide again.". This is because of auto logging out through lynda-dl. THen the cookie is invalid. Login with username and password s not possible, since authentication is made through the organisation portal...
> 
> Is this a known bug?

no its not a bug, this tool don't support SSO based logins, so if your cookies got expired you have to provide again.

i have tested with the courses links, for me it works fine it does not matter if you provide all the junk in front of that course url the tool work just with the url looks like the above one.

**Comment by manu212** [comment]
@r0oth3x49  thanks for your imemdiate feedback. Since I have only a SSO based login, I didn't know that. Thanks for explaining this.

**Comment by hong1999** [comment]
> @r0oth3x49 thanks for your imemdiate feedback. Since I have only a SSO based login, I didn't know that. Thanks for explaining this.

I'm using Library Account, facing the same "cookies" issue with you, do you have any solution?
