### ISSUE TITLE
@AntiGov the error could be resolved by providing the new cookies, the session gets expired which leads to this error, so if you refresh your session in browser and provide the cookie again it will work fine.

### ISSUE THREAD

**Issue by hong1999** [r0oth3x49/lynda-dl#67]
@AntiGov the error could be resolved by providing the new cookies, the session gets expired which leads to this error, so if you refresh your session in browser and provide the cookie again it will work fine.

_Originally posted by @r0oth3x49 in https://github.com/r0oth3x49/lynda-dl/issues/55#issuecomment-495885111_

**Comment by hong1999** [comment]
![image](https://user-images.githubusercontent.com/32258161/58762184-fdfbf700-857f-11e9-9d09-2219f2b45384.png)
I run into the same issue, had tried your solution but it appears again under the same link. When I first have this problem, I refresh my browser, then run a second time, the same link has the same problem again

**Comment by 01ttouch** [comment]
You can download my fork here which already fixed the problem
https://github.com/01ttouch/lynda-dl/archive/bug-login-with-cookie.zip

**Comment by hong1999** [comment]
> You can download my fork here which already fixed the problem
> https://github.com/01ttouch/lynda-dl/archive/bug-login-with-cookie.zip

![image](https://user-images.githubusercontent.com/32258161/58798880-6f967c80-8636-11e9-9f71-32ba6f13c200.png)
Seem like the problem still there

**Comment by hong1999** [comment]
> You can download my fork here which already fixed the problem
> https://github.com/01ttouch/lynda-dl/archive/bug-login-with-cookie.zip

![image](https://user-images.githubusercontent.com/32258161/58799335-a620c700-8637-11e9-9c50-62494aa9936c.png)
When I first log in using my library, in the middle, this happened

**Comment by 01ttouch** [comment]
It's been 5 hours since the last time i changed the cookie file and i still login and download fine.

Look like it's a problem on some specific courses. Can you provide the link you trying to download and got the error.

**Comment by hong1999** [comment]
After doing some debug, I found out that this link was causing the problem https://www.lynda.com/MicroStation-tutorials/Microstation-Reference-Files/624269-2.html

**Comment by 01ttouch** [comment]
@hong1999
The course doesn't have subtitle and that's cause the problem.
You can clone here which fixed the problem: https://github.com/01ttouch/lynda-dl/archive/fixed.zip

**Comment by hong1999** [comment]
> @hong1999
> The course doesn't have subtitle and that's cause the problem.
> You can clone here which fixed the problem: https://github.com/01ttouch/lynda-dl/archive/fixed.zip

![image](https://user-images.githubusercontent.com/32258161/58848004-787b6280-86b7-11e9-94bd-f6d12fe4864f.png)
Problem Solved, no more cookies expired, thank you very much
