### ISSUE TITLE
LinkedIn Learning Support 

### ISSUE THREAD

**Issue by eyanq** [r0oth3x49/lynda-dl#73]
Hi @r0oth3x49,

Do you have any plans to support LinkedIn Learning?

According to LinkedIn [here](https://www.linkedin.com/help/lynda/answer/90509/for-individual-subscribers-moving-from-lynda-com-to-linkedin-learning-faqs?lang=en),

> LinkedIn Learning is the next generation of Lynda.com. It has all the same content as Lynda.com, but with special insights and social engagement that only LinkedIn can additionally offer. Our goal is to help people discover and develop the skills they need through a personalized, data-driven learning experience.

Cheers.

**Comment by r0oth3x49** [comment]
@yan9yu it was requested before but i guess it requires some premium account to access courses and currently i haven't subscribed to any, so i might need a test account to check & implement

**Comment by avelytchko** [comment]
There is a free one-month trial account so you have enough time to check I think.
