### ISSUE TITLE
Connection error : make sure your internet connection is working

### ISSUE THREAD

**Issue by hong1999** [r0oth3x49/lynda-dl#77]
Looks like this has some issue
Windows 10 
Python 3.7.7 
PIP  20.0.2
All package upgrade to newest version 

In the middle 
[+] : Found (49) courses ..
[*] : Trying to login as organization (-------)...
[-] : Connection error : make sure your internet connection is working.

I'm sure my internet is working as I'm running another edx downloader.

When I change to cookie download 
[+] : Found (49) courses ..
[*] : Trying to login using cookies ...
[-] : Cookies error, Request Headers is required.
[i] : Copy Request Headers for single request to a file, while you are logged in

**Comment by federa7675** [comment]
+1

**Comment by federa7675** [comment]
It started workin again!

**Comment by hong1999** [comment]
> It started workin again!

yeah, it works now, maybe there is some issue with one or more of the pip package

**Comment by r0oth3x49** [comment]
so should we close the issue or what?
