### ISSUE TITLE
IOError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by spinnaker1** [r0oth3x49/lynda-dl#78]
Lynda-dl is giving me this error: `IOError: [Errno 5] Input/output error ` and stopped when downloading this course. Please see the command and response below:

`python lynda-dl.py -u XXXXXX -p XXXXX -d /media/lynda/ -q 540 https://www.lynda.com/Business-tutorials/Financial-Accounting-Part-2/713376-2.html`

```
[*] : Downloaded course information .. (done)
[*] : Trying to logout now...
[+] : Logged out successfully.
[*] : Course 'Financial Accounting Part 2'.
[+] : Chapter(s) (12).
[*] : Lecture(s) (59).

[*] : Downloading chapter : (1 of 12)
[+] : Chapter (01 Introduction)
[*] : Found (1) lectures ...

[*] : Lecture(s) : (1 of 1)
[*] : Downloading (001 Financial analysis cash flow analysis and valuation)
[*] : Lecture : '001 Financial analysis cash flow analysis and valuation' (already downloaded).

[*] : Downloading chapter : (2 of 12)
[+] : Chapter (02 Quick Review of Financial Statements)
[*] : Found (4) lectures ...

[*] : Lecture(s) : (1 of 4)
[*] : Downloading (001 Who uses financial statements_)
[*] : Lecture : '001 Who uses financial statements_' (already downloaded).

[*] : Lecture(s) : (2 of 4)
[*] : Downloading (002 Review of the balance sheet)
[*] : Lecture : '002 Review of the balance sheet' (already downloaded).

[*] : Lecture(s) : (3 of 4)
[*] : Downloading (003 Review of the income statement)
[*] : 9.09MB/9.09MB 100.00% |##############################| 4.87MB/s
Traceback (most recent call last):
  File "lynda-dl.py", line 395, in <module>
    main()
  File "lynda-dl.py", line 391, in main
    lynda.course_download(path=options.output, quality=options.quality)
  File "lynda-dl.py", line 205, in course_download
    self.download_lectures_and_captions(lecture_best=lecture_best, lecture_title=lecture_title, inner_index=lecture_index, lectures_count=lectures_count, subtitle=lecture_subtitles, filepath=filepath)
  File "lynda-dl.py", line 150, in download_lectures_and_captions
    self.download_lectures(lecture_best=lecture_best, lecture_title=lecture_title, inner_index=inner_index, lectures_count=lectures_count, filepath=filepath)
  File "lynda-dl.py", line 127, in download_lectures
    retval = lecture_best.download(filepath=filepath, quiet=True, callback=self.show_progress)
  File "/root/lynda-dl/lynda/_shared.py", line 438, in download
    outfh.close()
IOError: [Errno 5] Input/output error
```

**Comment by codencoffe** [comment]
> Lynda-dl is giving me this error: `IOError: [Errno 5] Input/output error ` and stopped when downloading this course. Please see the command and response below:
> 
> `python lynda-dl.py -u XXXXXX -p XXXXX -d /media/lynda/ -q 540 https://www.lynda.com/Business-tutorials/Financial-Accounting-Part-2/713376-2.html`
> 
> ```
> [*] : Downloaded course information .. (done)
> [*] : Trying to logout now...
> [+] : Logged out successfully.
> [*] : Course 'Financial Accounting Part 2'.
> [+] : Chapter(s) (12).
> [*] : Lecture(s) (59).
> 
> [*] : Downloading chapter : (1 of 12)
> [+] : Chapter (01 Introduction)
> [*] : Found (1) lectures ...
> 
> [*] : Lecture(s) : (1 of 1)
> [*] : Downloading (001 Financial analysis cash flow analysis and valuation)
> [*] : Lecture : '001 Financial analysis cash flow analysis and valuation' (already downloaded).
> 
> [*] : Downloading chapter : (2 of 12)
> [+] : Chapter (02 Quick Review of Financial Statements)
> [*] : Found (4) lectures ...
> 
> [*] : Lecture(s) : (1 of 4)
> [*] : Downloading (001 Who uses financial statements_)
> [*] : Lecture : '001 Who uses financial statements_' (already downloaded).
> 
> [*] : Lecture(s) : (2 of 4)
> [*] : Downloading (002 Review of the balance sheet)
> [*] : Lecture : '002 Review of the balance sheet' (already downloaded).
> 
> [*] : Lecture(s) : (3 of 4)
> [*] : Downloading (003 Review of the income statement)
> [*] : 9.09MB/9.09MB 100.00% |##############################| 4.87MB/s
> Traceback (most recent call last):
>   File "lynda-dl.py", line 395, in <module>
>     main()
>   File "lynda-dl.py", line 391, in main
>     lynda.course_download(path=options.output, quality=options.quality)
>   File "lynda-dl.py", line 205, in course_download
>     self.download_lectures_and_captions(lecture_best=lecture_best, lecture_title=lecture_title, inner_index=lecture_index, lectures_count=lectures_count, subtitle=lecture_subtitles, filepath=filepath)
>   File "lynda-dl.py", line 150, in download_lectures_and_captions
>     self.download_lectures(lecture_best=lecture_best, lecture_title=lecture_title, inner_index=inner_index, lectures_count=lectures_count, filepath=filepath)
>   File "lynda-dl.py", line 127, in download_lectures
>     retval = lecture_best.download(filepath=filepath, quiet=True, callback=self.show_progress)
>   File "/root/lynda-dl/lynda/_shared.py", line 438, in download
>     outfh.close()
> IOError: [Errno 5] Input/output error
> ```

Hello,
Have you tried 
1. using different quality e.g 720
2. using cookies.txt file
Thx

**Comment by r0oth3x49** [comment]
PR is welcome for the fix.
