### ISSUE TITLE
Feature request: Option to skip errors and continue download

### ISSUE THREAD

**Issue by spinnaker1** [r0oth3x49/lynda-dl#79]
If you provide lynda-dl a list of urls of courses and a single course download gives an error, it stops downloading and doesn't continue with the remaining courses.

**Is it possible to add a flag to skip an error and continue downloading with the remaining courses? Or just skip the specific video in that course and continue with next video in same course? **

For example youtube-dl provides that option:
```
-i, --ignore-errors              Continue on download errors, for example to
                                 skip unavailable videos in a playlist
```

```
-c, --continue                   Force resume of partially downloaded files.
                                 By default, youtube-dl will resume
                                 downloads if possible.
```

**Comment by r0oth3x49** [comment]
PRs are welcome, for now i don't have any plan to add this feature so i 'm going to close the issue
