### ISSUE TITLE
How to create a new cookie inside the cookies.txt file

### ISSUE THREAD

**Issue by caveman-2020** [r0oth3x49/lynda-dl#80]
On the comments it says that it can get expired and that we must create a new cookie file. Anybody knows how to do that?

Thanks!

**Comment by codencoffe** [comment]
> On the comments it says that it can get expired and that we must create a new cookie file. Anybody knows how to do that?
> 
> Thanks!

> On the comments it says that it can get expired and that we must create a new cookie file. Anybody knows how to do that?
> 
> Thanks!

In FireFox:
1. login to your lynda account
2. visit the course website
3. right click and choose "Inspect element" ( a small window will open at bottom or side showing html code of page)
4. inside this small window, choose network from menu
5. choose "XHR" from small menu beneath the network menu.
6.  a long list of item will be displayed inside small windos, right click on get request (I choose "play")option
7. from Righ-Click menu choose Copy->Copy Request Header
8. paste this inside a text file and save the file(e.g 123.txt) inside folder of lynda-dl.py.
9. now  use this file (123.txt) with "lynda-dl.py -k 123.txt course_URL ...."
10. Enjoy the course from your local [storage.!!!]

![lynda-dl jpg](https://user-images.githubusercontent.com/30585284/83962020-ad198f80-a8b2-11ea-81f9-dd757ef91b9b.png)
