### ISSUE TITLE
Cant login using cookies.

### ISSUE THREAD

**Issue by ambi1997** [r0oth3x49/lynda-dl#82]
Can anyone be specific what to put in the cookies.txt? 
I put the request headers in the cookies.txt file as specified in the README, but it's not working.

Thank you.

**Comment by nixklai** [comment]
Please check [this comment](https://github.com/r0oth3x49/lynda-dl/issues/80#issuecomment-640165445), although I do think it should be clearer on the documentation side.

**Comment by nixklai** [comment]
I think it is because of the behaviour of `lynda-dl` expecting a `token` cookie which no longer exists in LinkedIn Learning, as shown [here](https://github.com/r0oth3x49/lynda-dl/blob/6031cb69fd8bce086e9193d4aefa89a2f0861c1f/lynda/_auth.py#L163).

**Comment by ambi1997** [comment]
> I think it is because of the behaviour of `lynda-dl` expecting a `token` cookie which no longer exists in LinkedIn Learning, as shown [here](https://github.com/r0oth3x49/lynda-dl/blob/6031cb69fd8bce086e9193d4aefa89a2f0861c1f/lynda/_auth.py#L163).

I see.

**Comment by ambi1997** [comment]
Anyways, Thank you @nixklai  , I used youtube-dl to download them.

**Comment by nixklai** [comment]
@r0oth3x49 is there a plan on fixing it?

**Comment by r0oth3x49** [comment]
@nixklai can you share you cookies on my email `nasir251292@gmail.com`, so that i can check what is used to authenticate the user with Linkedin learning

**Comment by r0oth3x49** [comment]
btw @nixklai you should probably search the same course on `https://www.lynda.com/` and provide the url to download in your case it should be `https://www.lynda.com/InCopy-tutorials/Learning-InCopy/521143-2.html`

**Comment by r0oth3x49** [comment]
plus one more thing the cookie which you are providing is of linkedin not lynda, it only works with lynda not linkedin

**Comment by nixklai** [comment]
@r0oth3x49  I have sent you my cookie jar file with email. Since my account is an institute account so I can't give you my credential. However, here are some observations I noticed from LinkedIn Learning (LL) and other downloaders:
1. The `token` cookie no longer exist in LL, and is replaced with `li_at`
2. The subtitle track is now bundled with other materials and sends at `https://www.linkedin.com/learning-api/videos?decorationId=com.linkedin.learning.api.deco.content.DecoratedVideo-12&parentSlug={{course_slug}}&q=slugs&slug={{episode_slug}}`, which may require additional parsing.

**Comment by nixklai** [comment]
> plus one more thing the cookie which you are providing is of linkedin not lynda, it only works with lynda not linkedin

I think Lynda.com are phasing out after the acquisition by LinkedIn, so it may be a good idea to support LinkedIn Learning. My Lynda.com institute account got transferred to LinkedIn Learning awhile ago.

**Comment by r0oth3x49** [comment]
@nixklai this utility will only work with lynda.com not linkedin, while another thing which is checked is implementing linkedin updates are complex so PRs are welcome for that. closing the issue as won't fix
