### ISSUE TITLE
Issue: Downloading course information .. |[-] : Connection error : make sure your internet connection is working.

### ISSUE THREAD

**Issue by Aryansha86** [r0oth3x49/lynda-dl#86]
Hello Sir,

I am Facing this issue, mentioned below.

Please Help me about this... I will be waiting for reply...

 oooo                                .o8                      .o8  oooo
 `888                               "888                     "888  `888
  888  oooo    ooo ooo. .oo.    .oooo888   .oooo.        .oooo888   888
  888   `88.  .8'  `888P"Y88b  d88' `888  `P  )88b      d88' `888   888
  888    `88..8'    888   888  888   888   .oP"888 8888 888   888   888
  888     `888'     888   888  888   888  d8(  888      888   888   888
 o888o     .8'     o888o o888o `Y8bod88P" `Y888""8o     `Y8bod88P" o888o
       .o..P'
       `Y8P'                            Version : 0.3
                                        Author  : Nasir Khan (r0ot h3x49)
                                        Github  : https://github.com/r0oth3x49

[*] : Trying to login as organization (___________________)...
[+] : Logged in successfully.
[*] : Downloading course information .. |[-] : Connection error : make sure your internet connection is working.

C:\Users\saura\Downloads\lynda-dl-master (1)\lynda-dl-master>

**Comment by r0oth3x49** [comment]
PRs are welcome if you can fix it i will merge the PR.
