### ISSUE TITLE
error FileNotFoundError: [Errno 2] No such file or directory...

### ISSUE THREAD

**Issue by Mozenrat** [r0oth3x49/lynda-dl#9]
Hi.
Getting following error while downloading some courses. Example: Silverlight 5 Essential Training, error happens during part 19th (though in the error line it's says 20 for some reason):
```
[*] : Downloading lecture : (1 of 8)
[*] : Downloading (001 Understanding Silverlight animations )
Traceback (most recent call last):
  File "C:\Users\usver\scripts\lynda-dl\lynda-dl.py", line 433, in <module>
    main()
  File "C:\Users\usver\scripts\lynda-dl\lynda-dl.py", line 405, in main
    lynda.InfoExtractor()
  File "C:\Users\usver\scripts\lynda-dl\lynda-dl.py", line 181, in InfoExtractor
    out = self.Downloader(_url, lecture_name, chapter_path)
  File "C:\Users\usver\scripts\lynda-dl\lynda-dl.py", line 88, in Downloader
    out = course_dl.download(url, title, filepath=path, quiet=True, callback=self.Download)
  File "C:\Users\usver\scripts\lynda-dl\lynda\_downloader.py", line 85, in download
    outfh = open(temp_filepath, fmode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\usver\\scripts\\lynda-dl\\_DL\\Silverlight-5-Essential-Training\\20  Energizing the UI with Animations \\001 Understanding Silverlight animations .mp4.temp'
```

Update:  Another example: "AutoCAD 2019 Essential Training", error happens with the first video.

**Comment by r0oth3x49** [comment]
@Mozenrat i will check and fix ASAP. can you please provide course URL so that i can test it against that course.

**Comment by Mozenrat** [comment]
thank you!
Here are URLs:
https://www.lynda.com/Silverlight-tutorials/Silverlight-5-Essential-Training/87898-2.html
https://www.lynda.com/AutoCAD-tutorials/AutoCAD-2019-Essential-Training/656793-2.html

**Comment by r0oth3x49** [comment]
@Mozenrat try downloading course to any other drive. -o "E:\lynda"

**Comment by ghalebi1886** [comment]
@r0oth3x49 I have the same issue, what should I do? I am on mac os
